/* AUTO-GENERATED by scripts/build_online_site.py — do not edit.
   Body markup of the app (login + shell + modals), identical to the
   offline build plus the online bits (month select, upload switch,
   offline-copy link). Served via dangerouslySetInnerHTML — static,
   app-owned markup only. */
export const SKELETON_HTML = `<!-- ================= Login screen (round 10 — denim edition) =================
     Full-screen factory-identity gate: dark-denim weave, leather patch,
     stitched fields, sewing-machine password animation. -->
<div class="login" id="loginScreen" lang="ar">
  <div class="lg-bg" aria-hidden="true">
    <svg class="lg-mach-bg" viewBox="0 0 360 320" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round">
      <path d="M20 292 H340"/>
      <path d="M40 292 V262 H320 V292"/>
      <path d="M52 262 V96"/>
      <path d="M52 96 Q60 66 92 66 H268 Q302 66 302 96 V150"/>
      <path d="M302 150 V204"/>
      <circle cx="100" cy="84" r="26"/>
      <path d="M100 58 v52 M74 84 h52"/>
      <rect x="146" y="34" width="30" height="30" rx="5"/>
      <path d="M161 64 V66"/>
      <path d="M161 66 C 161 130, 268 130, 276 210" stroke-width="4"/>
      <path d="M276 210 V252"/>
      <path d="M258 258 H296"/>
    </svg>
    <div class="lg-pocket"><i class="pk-stitch"></i><b class="pk-rivet ra"></b><b class="pk-rivet rb"></b></div>
    <svg class="lg-spool-bg" viewBox="0 0 130 160" fill="none">
      <rect x="30" y="16" width="70" height="16" rx="5" fill="#7A5A38" stroke="#A98A5F" stroke-width="2"/>
      <rect x="40" y="32" width="50" height="84" rx="7" fill="#B08A54"/>
      <path d="M44 40 h42 M44 50 h42 M44 60 h42 M44 70 h42 M44 80 h42 M44 90 h42 M44 100 h42 M44 108 h42" stroke="#8A683C" stroke-width="3"/>
      <rect x="30" y="116" width="70" height="16" rx="5" fill="#7A5A38" stroke="#A98A5F" stroke-width="2"/>
      <path d="M65 132 C 60 150, 30 150, 8 138" stroke="#C9A227" stroke-width="2.5" stroke-dasharray="1 6" stroke-linecap="round"/>
    </svg>
    <svg class="lg-thread-bg" viewBox="0 0 900 520" fill="none" preserveAspectRatio="none">
      <path d="M-20 140 C 180 40, 360 240, 560 120 S 820 60, 940 170" stroke="#D9A86B" stroke-width="2.5" stroke-dasharray="10 8" stroke-linecap="round"/>
      <path d="M873 156 l 30 -64" stroke="#D9A86B" stroke-width="3" stroke-linecap="round"/>
      <circle cx="876" cy="158" r="3.5" fill="#D9A86B"/>
    </svg>
    <div class="lg-glow"></div>
    <div class="lg-sweep"></div>
    <div class="lg-vign"></div>
  </div>

  <!-- language bar — page level, top far LEFT, OUTSIDE the card (round 11) -->
  <div class="lg-lang" id="lgLang" role="group" aria-label="Language">
    <svg class="lg-lang-ic" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3.2 12h17.6"/><path d="M12 3c3.1 3.7 3.1 14.3 0 18M12 3c-3.1 3.7-3.1 14.3 0 18"/></svg>
    <button data-lg="ar" class="on" type="button">ع</button>
    <button data-lg="en" type="button">EN</button>
    <button data-lg="tr" type="button">TR</button>
  </div>

  <div class="lg-card" role="dialog" aria-labelledby="lgTitle">
    <b class="rv rv-tl"></b><b class="rv rv-tr"></b><b class="rv rv-bl"></b><b class="rv rv-br"></b>

    <!-- leather patch = company identity: real logo on a woven cream label +
         company name written in the page language + dashboard name -->
    <div class="lg-leather">
      <span class="lg-label"><img id="lgCoLogo" alt="" aria-hidden="true"></span>
      <b class="lg-co" data-i18n="brand_name">مأرب العالمية للملابس الجاهزة</b>
      <span class="lg-patch-sub" data-i18n="lg_sub">لوحة أداء مصنع مأرب</span>
    </div>
    <div class="lg-sign" aria-hidden="true">MARIB&nbsp;PERFORMANCE</div>

    <h2 id="lgTitle" data-i18n="lg_welcome">مرحبًا بك</h2>
    <p class="lg-hint" data-i18n="lg_hint">يرجى تسجيل الدخول للمتابعة</p>

    <form id="lgForm" novalidate>
      <div class="lfield">
        <svg class="lf-ic" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="8" r="3.6"/><path d="M5.5 20c.8-4 3.4-6 6.5-6s5.7 2 6.5 6"/></svg>
        <input id="lgUser" type="text" autocomplete="username" spellcheck="false" data-i18n-ph="lg_user_ph" data-i18n-aria="lg_user_ph" aria-label="اسم المستخدم" placeholder="اسم المستخدم">
      </div>

      <div class="lfield pw" id="lgPwField" dir="ltr">
        <svg class="lf-ic" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="5.5" y="10.5" width="13" height="9" rx="2.5"/><path d="M8.5 10.5V8a3.5 3.5 0 0 1 7 0v2.5"/><circle cx="12" cy="15" r="1.2" fill="currentColor"/></svg>
        <input id="lgPass" type="password" autocomplete="current-password" data-i18n-ph="lg_pass_ph" data-i18n-aria="lg_pass_ph" aria-label="كلمة المرور" placeholder="كلمة المرور">
        <button type="button" class="pw-toggle" id="lgEye" aria-pressed="false" aria-label="إظهار كلمة المرور" data-i18n-aria="lg_act_show" title="">
          <svg class="ic-spool" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <rect x="6.5" y="3.5" width="11" height="3" rx="1.2"/>
            <rect x="6.5" y="17.5" width="11" height="3" rx="1.2"/>
            <path d="M8.6 6.5v11M15.4 6.5v11" stroke-width="1.1"/>
            <path d="M8.6 9h6.8M8.6 11.5h6.8M8.6 14h6.8" stroke-width="1.1"/>
            <path d="M12 20.5q3 .8 3 2.3" stroke-width="1.3"/>
          </svg>
          <svg class="ic-rip" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <g transform="rotate(45 16 8)"><rect x="13.6" y="2.6" width="5" height="10" rx="2.4"/></g>
            <path d="M5.5 18.5 L14.8 9.2"/>
            <path d="M5.5 18.5 c-2 .4-3 1.8-2.6 3.4" stroke-width="1.4"/>
            <circle cx="4.1" cy="20.6" r="1" fill="currentColor" stroke="none"/>
          </svg>
        </button>
        <div class="pw-theater" id="pwTheater" aria-hidden="true">
          <!-- round 14: thread width fixed in JS so its viewBox maps 1:1 to
               real pixels — it follows the needle exactly and never leaves
               the input bar.
               round 20: paint order is set by z-index in login_style.css
               (mirror 1 < stitch 2 < thread 3 < mach 4 < rip 5) — DOM order
               here is historical; the OPAQUE mirror used to eat the lower
               body of the machine + the in-strip thread when it painted
               after them. -->
          <svg class="pw-thread" id="pwThread" fill="none" aria-hidden="true"><path id="pwThreadPath" stroke="#C9A227" stroke-width="1.6" stroke-linecap="round" opacity=".75"/></svg>
          <svg class="pw-mach" id="pwMach" viewBox="0 0 96 110">
            <defs>
              <linearGradient id="pwMBody" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0" stop-color="#A7B4BF"/>
                <stop offset=".55" stop-color="#6B7681"/>
                <stop offset="1" stop-color="#434C56"/>
              </linearGradient>
              <linearGradient id="pwMTan" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0" stop-color="#D8AC72"/>
                <stop offset="1" stop-color="#A87F4E"/>
              </linearGradient>
            </defs>
            <rect x="2" y="90" width="74" height="12" rx="4" fill="url(#pwMBody)"/>
            <rect x="4" y="44" width="18" height="48" rx="5" fill="url(#pwMBody)"/>
            <rect x="4" y="30" width="76" height="16" rx="8" fill="url(#pwMBody)"/>
            <rect x="60" y="30" width="20" height="32" rx="5" fill="url(#pwMBody)"/>
            <circle cx="13" cy="38" r="8.5" fill="#5A4630" stroke="#C49A6C" stroke-width="2"/>
            <circle cx="13" cy="38" r="3" fill="#C49A6C"/>
            <rect x="40" y="24" width="5" height="7" rx="1.5" fill="#8E9AA6"/>
            <rect x="36" y="13" width="13" height="12" rx="3" fill="url(#pwMTan)"/>
            <path d="M38.5 16h8M38.5 19h8M38.5 22h8" stroke="#8A683C" stroke-width="1"/>
            <circle cx="55" cy="27" r="2" fill="#C9A227"/>
            <path d="M42 25 C 46 32, 54 36, 60 42" stroke="#C9A227" stroke-width="1.3" fill="none"/>
            <g class="pw-needle">
              <rect x="67" y="62" width="5" height="24" rx="2" fill="#B9C2CC"/>
              <rect x="68.6" y="84" width="1.8" height="18" rx=".9" fill="#E5EAEF"/>
              <path d="M69.5 102 l0 3" stroke="#C9A227" stroke-width="1"/>
            </g>
            <path d="M62 88 h14 l-3 5 h-8 z" fill="#C49A6C"/>
          </svg>
          <div class="pw-mirror" id="pwMirror"></div>
          <svg class="pw-stitch-svg" id="pwStitchSvg" fill="none" preserveAspectRatio="none" aria-hidden="true">
            <path id="pwStitchGlow" stroke="#D9A86B" stroke-width="6" stroke-linecap="round" stroke-dasharray="9 6.5" opacity=".16"/>
            <path id="pwStitchPath" stroke="#D9A86B" stroke-width="2.6" stroke-linecap="round" stroke-dasharray="9 6.5" opacity=".96"/>
          </svg>
          <svg class="pw-rip" id="pwRip" viewBox="0 0 40 64" fill="none" aria-hidden="true">
            <rect x="13" y="2" width="13" height="30" rx="6" fill="#8A683C" stroke="#C49A6C" stroke-width="1.5"/>
            <path d="M17 8 h5 M17 26 h5" stroke="#C49A6C" stroke-width="1.2" opacity=".7"/>
            <rect x="17.8" y="32" width="3.4" height="17" rx="1.6" fill="#B9C2CC"/>
            <path d="M19.5 49 c5.5 2.5, 7 8, 3.6 12.5" stroke="#D9E0E7" stroke-width="2.6" stroke-linecap="round"/>
            <circle cx="23.4" cy="61" r="2.4" fill="#D96A5A"/>
          </svg>
        </div>
      </div>

      <div class="lg-opts">
        <label class="lg-remember">
          <input type="checkbox" id="lgRemember"><i></i><span data-i18n="lg_remember">تذكرني</span>
        </label>
        <a class="lg-forgot" href="#" id="lgForgot" data-i18n="lg_forgot">نسيت كلمة المرور؟</a>
      </div>

      <button class="lg-submit" type="submit" id="lgSubmit">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <path d="M3 20.5h14.5"/><path d="M5 20.5V9.5q0-2.5 2.5-2.5H8"/><path d="M8 7h8q3 0 3 3.2V15"/>
          <circle cx="6.3" cy="4.6" r="2.1"/><path d="M16.6 15v5.5"/><path d="M13.6 20.5h5"/>
          <rect x="10.6" y="2.9" width="3.2" height="2.5" rx=".8" stroke-width="1.2"/>
        </svg>
        <span data-i18n="lg_login">تسجيل الدخول</span>
        <i class="lg-run"></i>
      </button>
      <p class="lg-err" id="lgErr" aria-live="polite"></p>
    </form>
  </div>
  <p class="sr-only" id="lgStatus" aria-live="polite"></p>
</div>

<div class="bg-fx"></div>
<div class="shell">

  <!-- ================= Topbar ================= -->
  <header class="topbar">
    <div class="brand">
      <img class="logo" id="brandLogo" alt="Marib Garments">
      <div class="brand-t">
        <h1 data-i18n="brand_name">مأرب للملابس</h1>
        <small data-i18n="brand_sub">MARIB&nbsp;GARMENTS</small>
      </div>
    </div>
    <div class="mid-title">
      <h2 data-i18n="mid_title">لوحة أداء المصنع</h2>
      <span data-i18n="mid_sub">MARIB&nbsp;PERFORMANCE</span>
    </div>
    <div class="ctrls">
      <div class="lang-sw" id="langSw">
        <button class="sw-btn on" data-lang="ar" type="button" title="العربية">ع</button>
        <button class="sw-btn" data-lang="en" type="button" title="English">EN</button>
        <button class="sw-btn" data-lang="tr" type="button" title="Türkçe">TR</button>
      </div>
      <span class="live"><i></i><span data-i18n="live">مباشر</span></span>
      <span class="date-chip num" id="dateChip">—</span>
      <span class="user-chip" id="userChip" style="display:none">
        <i class="uc-av" id="ucAv">—</i>
        <b id="ucName">—</b>
        <em class="uc-role" id="ucRole">—</em>
      </span>
    </div>
  </header>

  <!-- ================= Layout ================= -->
  <div class="layout">

    <!-- Sidebar (right in RTL) -->
    <aside class="sidebar">
      <!-- round 13: nav tabs are real <a href="#page"> links now —
         right-click gives the browser's LINK menu ("open in new tab"),
         ctrl/cmd/middle-click open the page in a new tab natively, and
         a plain click still navigates inside the SPA (see app_c.js) -->
    <a class="nav-btn on" data-page="overview" href="#overview" data-i18n-title="nav_tt_overview" title="الرئيسية">
      <span data-i18n="nav_overview">الرئيسية</span>
    </a>
    <a class="nav-btn" data-page="lines" href="#lines" data-i18n-title="nav_tt_lines" title="الخطوط">
      <span data-i18n="nav_lines">الخطوط</span>
    </a>
    <a class="nav-btn" data-page="sections" href="#sections" data-i18n-title="nav_tt_sections" title="تحليل الأقسام">
      <span data-i18n="nav_sections">الأقسام</span>
    </a>
    <a class="nav-btn" data-page="sups" href="#sups" data-i18n-title="nav_tt_sups" title="المشرفين">
      <span data-i18n="nav_sups">المشرفين</span>
    </a>
    <a class="nav-btn" data-page="pm" href="#pm" data-i18n-title="nav_tt_pm" title="تحليل ماكينات الجيوب">
      <span data-i18n="nav_pm">الجيوب</span>
    </a>
    <a class="nav-btn" data-page="ot" href="#ot" data-i18n-title="nav_tt_ot" title="الأوفر تايم">
      <span data-i18n="nav_ot">الأوفر تايم</span>
    </a>
    <a class="nav-btn" data-page="att" href="#att" data-i18n-title="nav_tt_att" title="الحضور">
      <span data-i18n="nav_att">الحضور</span>
    </a>

      <div class="spacer"></div>

      <div class="data-wrap">
        <button class="side-btn" id="btnUsers" style="display:none" data-i18n-title="nav_tt_users" title="المستخدمين" type="button">
          <span data-i18n="nav_users">المستخدمين</span>
        </button>
        <button class="data-btn" id="btnData" data-i18n-title="nav_tt_data" title="البيانات">
          <span data-i18n="nav_data">البيانات</span>
        </button>
        <button class="side-btn out" id="btnLogout" style="display:none" data-i18n-title="nav_tt_logout" title="تسجيل الخروج" type="button">
          <span data-i18n="nav_logout">خروج</span>
        </button>
        <a class="side-btn" href="/Marib_Performance_Studio.html" download="Marib_Performance_Studio.html" data-i18n-title="nav_tt_offline" title="نسخة الأوفلاين">
          <span data-i18n="nav_offline">أوفلاين</span>
        </a>
      </div>
    </aside>

    <!-- Content -->
    <main class="content">
      <div class="no-data" id="noData">
        <div class="nd-box">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3.5 6.8q0-1.6 1.6-1.6h4.2l2 2.6h7.6q1.6 0 1.6 1.6v8.2q0 1.6-1.6 1.6H5.1q-1.6 0-1.6-1.6z"/><path d="M3.5 10.6h17"/><path d="M8 14.4h4.5"/></svg>
          <h3 data-i18n="nd_title">اللوحة فاضية</h3>
          <p data-i18n="nd_hint">ارفع مجلد ملفات إكسل بتاع الشهر — كل التحليلات والرسومات بتتحدث فورًا على جهازك</p>
          <button class="nd-btn" id="ndBtn" type="button" data-i18n="nd_btn">رفع مجلد البيانات</button>
        </div>
      </div>
      <div class="page-ctrls">
        <div>
          <h3 id="pageTitle" data-i18n="pg_overview:0">الأداء العام</h3>
          <span class="sub" id="pageSub" data-i18n="pg_overview:1">FACTORY&nbsp;OVERVIEW</span>
        </div>
        <div class="filters">
          <select id="fMonth" title="الشهر" data-i18n-title="f_month"></select>
          <div class="qp" id="qp">
            <button class="qp-btn" data-qp="last1" data-i18n="f_last1" type="button">آخر يوم</button>
            <button class="qp-btn" data-qp="last7" data-i18n="f_last7" type="button">آخر أسبوع</button>
            <button class="qp-btn" data-qp="last30" data-i18n="f_last30" type="button">آخر شهر</button>
            <button class="qp-btn on" data-qp="all" data-i18n="f_all" type="button">الكل</button>
          </div>
          <div class="range-pick">
            <input type="date" id="fFrom" title="من" data-i18n-title="f_from">
            <span class="sep">—</span>
            <input type="date" id="fTo" title="إلى" data-i18n-title="f_to">
          </div>
          <select id="fLine" title="الخط" data-i18n-title="f_line"></select>
          <select id="fSection" title="القسم" data-i18n-title="f_section"></select>
          <select id="fSup" title="المشرف" data-i18n-title="f_sup"></select>
          <button class="icon-btn" id="btnTargets" title="الأهداف" data-i18n-title="f_targets" type="button">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="8.2"/><circle cx="12" cy="12" r="4"/><circle cx="12" cy="12" r="0.6" fill="currentColor"/></svg>
          </button>
          <button class="icon-btn" id="btnCsv" title="تصدير CSV" data-i18n-title="f_csv">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3.6v11.8m0 0-4.1-4.1M12 15.4l4.1-4.1M4.5 19.5h15"/></svg>
          </button>
        </div>
      </div>

      <div class="pages">

        <!-- ========== Overview ========== -->
        <section class="page on" id="page-overview">
          <div class="kpi-grid" id="ovKpis"></div>
          <div class="card hero-wrap row-16">
            <div class="card-head">
              <div>
                <h4 data-i18n="c_ovTrend:0">الإنتاج اليومي مقابل الهدف</h4>
                <span class="en" data-i18n="c_ovTrend:1">DAILY&nbsp;OUTPUT&nbsp;VS&nbsp;TARGET</span>
              </div>
              <span class="hero-head-chip" id="ovHeroChip"></span>
            </div>
            <div class="chart" id="ovTrend"></div>
          </div>
          <div class="grid-3">
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_ovTop:0">أفضل الخطوط تحقيقًا</h4><span class="en" data-i18n="c_ovTop:1">TOP&nbsp;LINES</span></div>
              </div>
              <div class="chart" id="ovTop"></div>
            </div>
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_ovDonut:0">توزيع الإنتاج على الأقسام</h4><span class="en" data-i18n="c_ovDonut:1">OUTPUT&nbsp;BY&nbsp;SECTION</span></div>
              </div>
              <div class="chart" id="ovDonut"></div>
            </div>
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_ovDual:0">الكفاءة والحضور اليومي</h4><span class="en" data-i18n="c_ovDual:1">EFFICIENCY&nbsp;&amp;&nbsp;ATTENDANCE</span></div>
              </div>
              <div class="chart" id="ovDual"></div>
            </div>
          </div>
        </section>

        <!-- ========== Lines ========== -->
        <section class="page" id="page-lines">
          <div class="kpi-grid strip" id="lnKpis"></div>
          <div class="grid-main2 row-16">
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_lnAchv:0">نسبة تحقيق الخطوط</h4><span class="en" data-i18n="c_lnAchv:1">LINE&nbsp;ACHIEVEMENT</span></div>
              </div>
              <div class="chart" id="lnAchv"></div>
            </div>
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_lnActual:0">الإنتاج الفعلي لكل خط</h4><span class="en" data-i18n="c_lnActual:1">ACTUAL&nbsp;BY&nbsp;LINE</span></div>
              </div>
              <div class="chart" id="lnActual"></div>
            </div>
          </div>
          <div class="card">
            <div class="card-head">
              <div><h4 data-i18n="c_lnTable:0">تفاصيل الخطوط</h4><span class="en" data-i18n="c_lnTable:1">LINE&nbsp;DETAILS</span></div>
              <span class="chip num" id="lnTblChip"></span>
            </div>
            <div class="tbl-wrap">
              <table class="tbl" id="lnTable"></table>
            </div>
          </div>
        </section>

        <!-- ========== Supervisors ========== -->
        <section class="page" id="page-sups">
          <div class="kpi-grid strip" id="svKpis"></div>
          <div class="grid-2 row-16">
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_svTop:0">الأعلى إنجازًا</h4><span class="en" data-i18n="c_svTop:1">TOP&nbsp;PERFORMERS</span></div>
              </div>
              <div class="chart" id="svTop"></div>
            </div>
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_svBottom:0">يحتاجون متابعة</h4><span class="en" data-i18n="c_svBottom:1">NEEDS&nbsp;ATTENTION</span></div>
              </div>
              <div class="chart" id="svBottom"></div>
            </div>
          </div>
          <div class="card">
            <div class="card-head">
              <div><h4 data-i18n="c_svTable:0">أداء المشرفين</h4><span class="en" data-i18n="c_svTable:1">SUPERVISOR&nbsp;DETAILS</span></div>
              <span class="chip num" id="svTblChip"></span>
            </div>
            <div class="tbl-wrap">
              <table class="tbl" id="svTable"></table>
            </div>
          </div>
        </section>

        <!-- ========== Sections ========== -->
        <section class="page" id="page-sections">
          <div class="kpi-grid strip" id="scKpis"></div>
          <div class="grid-main2 row-16">
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_scAchv:0">نسبة تحقيق الأقسام</h4><span class="en" data-i18n="c_scAchv:1">SECTION&nbsp;ACHIEVEMENT</span></div>
              </div>
              <div class="chart" id="scAchv"></div>
            </div>
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_scActual:0">الإنتاج الفعلي لكل قسم</h4><span class="en" data-i18n="c_scActual:1">ACTUAL&nbsp;BY&nbsp;SECTION</span></div>
              </div>
              <div class="chart" id="scActual"></div>
            </div>
          </div>
          <div class="card row-16">
            <div class="card-head">
              <div><h4 data-i18n="c_scTrend:0">الاتجاه اليومي للأقسام</h4><span class="en" data-i18n="c_scTrend:1">SECTION&nbsp;DAILY&nbsp;TREND</span></div>
              <span class="chip num" id="scTrendChip"></span>
            </div>
            <div class="chart" id="scTrend"></div>
          </div>
          <div class="card">
            <div class="card-head">
              <div><h4 data-i18n="c_scTable:0">تفاصيل الأقسام</h4><span class="en" data-i18n="c_scTable:1">SECTION&nbsp;DETAILS</span></div>
              <span class="chip num" id="scTblChip"></span>
            </div>
            <div class="tbl-wrap">
              <table class="tbl" id="scTable"></table>
            </div>
          </div>
        </section>

        <!-- ========== Pocket Machines ========== -->
        <section class="page" id="page-pm">
          <div class="kpi-grid strip" id="pmKpis"></div>
          <div class="grid-main2 row-16">
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_pmTrend:0">الاتجاه اليومي للماكينات</h4><span class="en" data-i18n="c_pmTrend:1">PM&nbsp;DAILY&nbsp;TREND</span></div>
              </div>
              <div class="chart" id="pmTrend"></div>
            </div>
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_pmMach:0">إنجاز الماكينات</h4><span class="en" data-i18n="c_pmMach:1">PM&nbsp;MACHINE&nbsp;ACHIEVEMENT</span></div>
              </div>
              <div class="chart" id="pmMach"></div>
            </div>
          </div>
          <div class="grid-2">
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_pmLine:0">إنتاج الماكينات حسب الخط</h4><span class="en" data-i18n="c_pmLine:1">PM&nbsp;BY&nbsp;LINE</span></div>
              </div>
              <div class="chart" id="pmLine"></div>
            </div>
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_pmTVsA:0">الهدف مقابل الفعلي حسب الخط</h4><span class="en" data-i18n="c_pmTVsA:1">TARGET&nbsp;VS&nbsp;ACTUAL</span></div>
              </div>
              <div class="chart" id="pmTVsA"></div>
            </div>
          </div>
          <div class="card">
            <div class="card-head">
              <div><h4 data-i18n="c_pmTable:0">تفاصيل ماكينات الجيوب</h4><span class="en" data-i18n="c_pmTable:1">POCKET&nbsp;MACHINE&nbsp;DETAILS</span></div>
              <span class="chip num" id="pmTblChip"></span>
            </div>
            <div class="tbl-wrap">
              <table class="tbl" id="pmTable"></table>
            </div>
          </div>
        </section>

        <!-- ========== Overtime ========== -->
        <section class="page" id="page-ot">
          <div class="kpi-grid strip" id="otKpis"></div>
          <div class="grid-main2 row-16">
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_otDaily:0">نسبة الأوفر تايم اليومية</h4><span class="en" data-i18n="c_otDaily:1">DAILY&nbsp;OVERTIME&nbsp;%</span></div>
              </div>
              <div class="chart" id="otDaily"></div>
            </div>
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_otGauge:0">مؤشر الأوفر تايم</h4><span class="en" data-i18n="c_otGauge:1">OVERTIME&nbsp;GAUGE</span></div>
              </div>
              <div class="chart" id="otGauge"></div>
              <div class="gauge-note">
                <span class="dot" style="background:rgba(47,213,131,.7)"></span><span data-i18n="gn_1">حتى 10%</span>
                <span class="dot" style="background:rgba(245,185,60,.7);margin-inline-start:10px"></span><span data-i18n="gn_2">10–20%</span>
                <span class="dot" style="background:rgba(248,113,113,.7);margin-inline-start:10px"></span><span data-i18n="gn_3">فوق 20%</span>
              </div>
            </div>
          </div>
          <div class="grid-2">
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_otSec:0">أوفر تايم الأقسام</h4><span class="en" data-i18n="c_otSec:1">OT&nbsp;BY&nbsp;SECTION</span></div>
              </div>
              <div class="chart" id="otSec"></div>
            </div>
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_otSrc:0">مصادر الدقائق المتاحة</h4><span class="en" data-i18n="c_otSrc:1">AVAILABLE&nbsp;MINUTES&nbsp;SOURCES</span></div>
              </div>
              <div class="chart" id="otSrc"></div>
            </div>
          </div>
          <div class="card row-16">
            <div class="card-head">
              <div><h4 data-i18n="c_otSup:0">أوفر تايم المشرفين</h4><span class="en" data-i18n="c_otSup:1">OT&nbsp;BY&nbsp;SUPERVISOR</span></div>
            </div>
            <div class="chart" id="otSup"></div>
          </div>
          <div class="card">
            <div class="card-head">
              <div><h4 data-i18n="c_otTable:0">تفاصيل الأوفر تايم اليومية</h4><span class="en" data-i18n="c_otTable:1">OT&nbsp;DAILY&nbsp;DETAILS</span></div>
              <span class="chip num" id="otTblChip"></span>
            </div>
            <div class="tbl-wrap">
              <table class="tbl" id="otTable"></table>
            </div>
          </div>
        </section>

        <!-- ========== Attendance ========== -->
        <section class="page" id="page-att">
          <div class="att-tabs" id="attTabs">
            <button class="att-tab on" data-attview="workers" type="button" data-i18n="at_tab_workers">حضور وغياب العمال</button>
            <button class="att-tab" data-attview="sups" type="button" data-i18n="at_tab_sups">حضور وغياب المشرفين</button>
          </div>

          <!-- ===== workers view ===== -->
          <div class="att-view on" id="attWorkers">
          <div class="kpi-grid strip" id="atKpis"></div>
          <div class="grid-main2 row-16">
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_atHeat:0">خريطة الانضباط الأسبوعية</h4><span class="en" data-i18n="c_atHeat:1">WEEKLY&nbsp;DISCIPLINE&nbsp;HEATMAP</span></div>
              </div>
              <div class="chart" id="atHeat"></div>
            </div>
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_atDow:0">متوسط الحضور حسب اليوم</h4><span class="en" data-i18n="c_atDow:1">ATTENDANCE&nbsp;BY&nbsp;WEEKDAY</span></div>
              </div>
              <div class="chart" id="atDow"></div>
            </div>
          </div>
          <div class="grid-2">
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_atDaily:0">الحضور اليومي</h4><span class="en" data-i18n="c_atDaily:1">DAILY&nbsp;ATTENDANCE</span></div>
              </div>
              <div class="chart" id="atDaily"></div>
            </div>
            <div class="card">
              <div class="card-head">
                <div><h4 data-i18n="c_atAbsent:0">إجمالي الغياب حسب اليوم</h4><span class="en" data-i18n="c_atAbsent:1">ABSENCES&nbsp;BY&nbsp;WEEKDAY</span></div>
              </div>
              <div class="chart" id="atAbsent"></div>
            </div>
          </div>
          <div class="card">
            <div class="card-head">
              <div><h4 data-i18n="c_atTable:0">تفاصيل الحضور اليومية</h4><span class="en" data-i18n="c_atTable:1">ATTENDANCE&nbsp;DAILY&nbsp;DETAILS</span></div>
              <span class="chip num" id="atTblChip"></span>
            </div>
            <div class="tbl-wrap">
              <table class="tbl" id="atTable"></table>
            </div>
          </div>
          </div>

          <!-- ===== supervisors view ===== -->
          <div class="att-view" id="attSups">
          <div class="kpi-grid strip" id="asKpis"></div>
          <div class="card">
            <div class="card-head">
              <div><h4 data-i18n="c_asDaily:0">المشرفون الحاضرون يوميًا</h4><span class="en" data-i18n="c_asDaily:1">SUPERVISORS&nbsp;PRESENT&nbsp;DAILY</span></div>
            </div>
            <div class="chart" id="asDaily"></div>
          </div>
          <div class="card">
            <div class="card-head">
              <div><h4 data-i18n="c_asTable:0">انضباط المشرفين</h4><span class="en" data-i18n="c_asTable:1">SUPERVISOR&nbsp;DISCIPLINE</span></div>
              <span class="chip num" id="asTblChip"></span>
            </div>
            <div class="tbl-wrap">
              <table class="tbl" id="asTable"></table>
            </div>
          </div>
          </div>
        </section>

      </div>
    </main>
  </div>
</div>

<!-- ================= Data menu modal ================= -->
<div class="data-pop" id="dataPop">
  <div class="dp-panel">
    <div class="dp-head">
      <div>
        <h3 data-i18n="dp_title">تحديث البيانات</h3>
        <span class="sub" data-i18n="dp_sub">DATA&nbsp;SOURCE</span>
      </div>
      <button class="icon-btn" id="dpClose" title="إغلاق" data-i18n-title="dp_close" type="button">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><path d="M6 6l12 12M18 6 6 18"/></svg>
      </button>
    </div>
    <button class="dp-act" id="actPick" type="button">
      <span class="dp-act-t" data-i18n="dp_pick">اختيار مجلد البيانات</span>
      <small data-i18n="dp_pick_hint">اختر ملفات إكسل الشهر من جهازك وتتحدّث اللوحة فورًا</small>
    </button>
    <p class="dp-empty-note" id="dpNote" data-i18n="dp_empty">اللوحة فاضية — ارفع مجلد الشهر عشان تشوف التحليلات</p>
  </div>
</div>

<!-- ================= Users & roles modal (round 10) ================= -->
<div class="data-pop" id="usPop">
  <div class="dp-panel us-panel">
    <div class="dp-head">
      <div>
        <h3 data-i18n="us_title">المستخدمين والصلاحيات</h3>
        <span class="sub" data-i18n="us_sub">USERS&nbsp;&amp;&nbsp;ROLES</span>
      </div>
      <button class="icon-btn" id="usClose" title="إغلاق" data-i18n-title="dp_close" type="button">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><path d="M6 6l12 12M18 6 6 18"/></svg>
      </button>
    </div>
    <div class="us-list" id="usList"></div>
    <div class="us-add">
      <h4 data-i18n="us_add_title">مستخدم جديد</h4>
      <div class="us-add-row">
        <input type="text" id="usName" autocomplete="off" spellcheck="false" data-i18n-ph="us_name_ph" data-i18n-aria="us_name_ph" placeholder="اسم المستخدم">
        <input type="text" id="usPass" autocomplete="off" data-i18n-ph="us_pass_ph" data-i18n-aria="us_pass_ph" placeholder="كلمة المرور">
      </div>
      <label class="us-chk">
        <input type="checkbox" id="usAdmin"><i></i><span data-i18n="us_admin_lbl">صلاحيات أدمن</span>
      </label>
      <label class="us-chk">
        <input type="checkbox" id="usUpload"><i></i><span data-i18n="us_upload_lbl">مسموح له يرفع الشهور</span>
      </label>
      <button class="us-add-btn" id="usAddBtn" type="button" data-i18n="us_add">إضافة المستخدم</button>
      <p class="us-note" data-i18n="us_admin_hint">الأدمن يقدر يضيف ويعدّل ويحذف المستخدمين — الحساب العادي بيشوف اللوحة بس</p>
    </div>
  </div>
</div>

<!-- ================= Targets settings modal ================= -->
<div class="data-pop" id="tgPop">
  <div class="dp-panel">
    <div class="dp-head">
      <div>
        <h3 data-i18n="tg_title">الأهداف والحدود</h3>
        <span class="sub" data-i18n="tg_sub">TARGETS&nbsp;&amp;&nbsp;THRESHOLDS</span>
      </div>
      <button class="icon-btn" id="tgClose" title="إغلاق" data-i18n-title="dp_close" type="button">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><path d="M6 6l12 12M18 6 6 18"/></svg>
      </button>
    </div>
    <div class="tg-grid" id="tgGrid">
      <div class="tg-row">
        <span class="tg-name" data-i18n="tg_achv">نسبة التحقيق</span>
        <label><i data-i18n="tg_goal">الهدف</i><input type="number" id="tgAchvGood" min="1" max="100" step="0.5"><u>%</u></label>
        <label><i data-i18n="tg_warn">تحذير</i><input type="number" id="tgAchvWarn" min="1" max="100" step="0.5"><u>%</u></label>
      </div>
      <div class="tg-row">
        <span class="tg-name" data-i18n="tg_eff">الكفاءة</span>
        <label><i data-i18n="tg_goal">الهدف</i><input type="number" id="tgEffGood" min="1" max="100" step="0.5"><u>%</u></label>
        <label><i data-i18n="tg_warn">تحذير</i><input type="number" id="tgEffWarn" min="1" max="100" step="0.5"><u>%</u></label>
      </div>
      <div class="tg-row">
        <span class="tg-name" data-i18n="tg_ot">الأوفر تايم</span>
        <label><i data-i18n="tg_safe">حد آمن</i><input type="number" id="tgOtGood" min="0.5" max="100" step="0.5"><u>%</u></label>
        <label><i data-i18n="tg_danger">خطر</i><input type="number" id="tgOtWarn" min="0.5" max="100" step="0.5"><u>%</u></label>
      </div>
      <div class="tg-row">
        <span class="tg-name" data-i18n="tg_att">الحضور</span>
        <label><i data-i18n="tg_goal">الهدف</i><input type="number" id="tgAttGood" min="1" max="100" step="0.5"><u>%</u></label>
        <label><i data-i18n="tg_warn">تحذير</i><input type="number" id="tgAttWarn" min="1" max="100" step="0.5"><u>%</u></label>
      </div>
    </div>
    <div class="tg-btns">
      <button class="tg-save" id="tgSave" type="button" data-i18n="tg_save">حفظ الأهداف</button>
      <button class="tg-reset" id="tgReset" type="button" data-i18n="tg_reset">القيم الافتراضية</button>
    </div>
    <p class="tg-note" data-i18n="tg_note">الأهداف تتحكم في خطوط الهدف على الرسومات وألوان الحالة في الجداول والمقاييس — وتُحفظ على جهازك.</p>
  </div>
</div>

<!-- ================= Drill-through modal ================= -->
<div class="drill" id="drill">
  <div class="drill-panel">
    <div class="drill-head">
      <div>
        <h3 id="drillTitle">—</h3>
        <span class="sub" id="drillSub">DETAILS</span>
      </div>
      <button class="icon-btn" id="drillClose" title="رجوع" data-i18n-title="d_close" type="button">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><path d="M6 6l12 12M18 6 6 18"/></svg>
      </button>
    </div>
    <div class="drill-kpis" id="drillKpis"></div>
    <div class="card" style="margin-bottom:14px">
      <div class="card-head">
        <div><h4 id="drillChartTitle" data-i18n="c_drillTrend:0">الاتجاه اليومي</h4><span class="en" data-i18n="c_drillTrend:1">DAILY&nbsp;TREND</span></div>
      </div>
      <div class="chart" id="drillChart"></div>
    </div>
    <div class="card">
      <div class="card-head">
        <div><h4 data-i18n="c_drillTable:0">السجلات التفصيلية</h4><span class="en" data-i18n="c_drillTable:1">DETAIL&nbsp;RECORDS</span></div>
        <span class="chip num" id="drillTblChip"></span>
      </div>
      <div class="tbl-wrap">
        <table class="tbl" id="drillTable"></table>
      </div>
    </div>
  </div>
</div>

<div id="tip"></div>
<div id="toast"></div>
<div id="dropZone">
  <div class="inner">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3.6v11.8m0 0-4.1-4.1M12 15.4l4.1-4.1M4.5 19.5h15"/></svg>
    <p data-i18n="dz_main">أفلت ملفات أو مجلد Excel هنا</p>
    <small data-i18n="dz_sub">يتم التحليل مباشرة على جهازك — بدون إنترنت</small>
  </div>
</div>
<input type="file" id="dirPick" webkitdirectory multiple hidden>`
